plugins {
    id 'com.android.application'
}

android {
    androidResources {
        noCompress += [
            "wasm",
            "data",
            "zip",
            "whl",
            "br",
            "gz",
            "bz2",
            "xz"
        ]
    }

    namespace 'com.malz.vs'
    compileSdk 34

    defaultConfig {
        applicationId 'com.malz.vs'
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName '2.0'
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
